Debugging

diff --git a/.github/workflows/login-test.yml b/.github/workflows/login-test.yml
--- a/.github/workflows/login-test.yml
+++ b/.github/workflows/login-test.yml
@@ -1,3 +1,14 @@
+# envsubst < .github/ci/docker-compose.yml > docker-compose.yml
+        # export TEST_RESULT=".github/testresults"
+        # EXECUTION_STRING=$(docker-compose -f docker-compose.yml up --abort-on-container-exit | grep 'Downloaded execution package')
+        # EXECUTION_ID=`echo ${EXECUTION_STRING##* }`
+        # curl -X GET "https://api.testproject.io/v2/projects/${{ secrets.TP_PROJECT_ID }}/jobs/${JOB_ID}/reports/${EXECUTION_ID}?details=true&format=TestProject" -H "accept: application/json" -H "Authorization: ${{ secrets.TP_API_KEY }}" | jq > ${TEST_RESULT}/login${EXECUTION_ID}.json
+        # RESULT=$(jq .resultType ${TEST_RESULT}/login${EXECUTION_ID}.json | sed 's/^.//;s/.$//')
+        # echo $EXECUTION_ID
+        # if [ $RESULT = 'Failed' ]; then echo "login test failed" && cat ${TEST_RESULT}/login${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
+        # rm ${TEST_RESULT}/login${EXECUTION_ID}.json
+        # 
+
 # if [ $RESULT='Failed' ]; then echo "login test failed" && cat ${TEST_RESULT}/login${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
 # This is a basic workflow to help you get started with Actions
 
@@ -15,6 +26,7 @@ on:
     branches: [ master ]
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
+# EXECUTION_ID=`echo ${EXECUTION_STRING##* }`
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -31,9 +43,5 @@ jobs:
         envsubst < .github/ci/docker-compose.yml > docker-compose.yml
         export TEST_RESULT=".github/testresults"
         EXECUTION_STRING=$(docker-compose -f docker-compose.yml up --abort-on-container-exit | grep 'Downloaded execution package')
-        EXECUTION_ID=`echo ${EXECUTION_STRING##* }`
-        curl -X GET "https://api.testproject.io/v2/projects/${{ secrets.TP_PROJECT_ID }}/jobs/${JOB_ID}/reports/${EXECUTION_ID}?details=true&format=TestProject" -H "accept: application/json" -H "Authorization: ${{ secrets.TP_API_KEY }}" | jq > ${TEST_RESULT}/login${EXECUTION_ID}.json
-        RESULT=$(jq .resultType ${TEST_RESULT}/login${EXECUTION_ID}.json | sed 's/^.//;s/.$//')
-        echo $EXECUTION_ID
-        if [ $RESULT = 'Failed' ]; then echo "login test failed" && cat ${TEST_RESULT}/login${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
-        rm ${TEST_RESULT}/login${EXECUTION_ID}.json
+        
+        echo $EXECUTION_STRING
