Login test added in new yml file inside workflows

diff --git a/.github/workflows/login-test.yml b/.github/workflows/login-test.yml
--- a/.github/workflows/login-test.yml
+++ b/.github/workflows/login-test.yml
@@ -1,7 +1,7 @@
 # if [ $RESULT='Failed' ]; then echo "login test failed" && cat ${TEST_RESULT}/login${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
 # This is a basic workflow to help you get started with Actions
 
-name: Failing job Tests
+name: Login Tests
 
 # Controls when the action will run. 
 on:
@@ -22,11 +22,11 @@ jobs:
     steps:
     - uses: actions/checkout@main
 
-    - name: Failing job Tests
+    - name: Run testProject Agent for Login Tests
       env:
-        TP_API_KEY: ${{ secrets.TP_API_KEY }}
-        APPLICATION_URL: ${{ secrets.APPLICATION_URL }} 
-        JOB_ID: 1vCI1WAo7U6X7Z0Oh4oMwQ
+        TP_API_KEY: ${{ secrets.TP_API_KEY }} # < Let Secrets handle your keys
+        APPLICATION_URL: ${{ secrets.APPLICATION_URL }}
+        JOB_ID: Q9WdIN3EEUyE437qx6fA9g # User login test
       run: |
         envsubst < .github/ci/docker-compose.yml > docker-compose.yml
         export TEST_RESULT=".github/testresults"
@@ -35,5 +35,5 @@ jobs:
         curl -X GET "https://api.testproject.io/v2/projects/${{ secrets.TP_PROJECT_ID }}/jobs/${JOB_ID}/reports/${EXECUTION_ID}?details=true&format=TestProject" -H "accept: application/json" -H "Authorization: ${{ secrets.TP_API_KEY }}" | jq > ${TEST_RESULT}/login${EXECUTION_ID}.json
         RESULT=$(jq .resultType ${TEST_RESULT}/login${EXECUTION_ID}.json | sed 's/^.//;s/.$//')
         echo $RESULT
-        if [ $RESULT = 'Failed' ]; then echo "Always failing test failed" && cat ${TEST_RESULT}/login${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
+        if [ $RESULT = 'Failed' ]; then echo "login test failed" && cat ${TEST_RESULT}/login${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
         rm ${TEST_RESULT}/login${EXECUTION_ID}.json
