Running test Published Host Barch Details Tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,3 +1,4 @@
+# if [ $RESULT='Failed' ]; then echo "login test failed" && cat ${TEST_RESULT}/login${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
 # This is a basic workflow to help you get started with Actions
 
 name: CI
@@ -21,11 +22,11 @@ jobs:
     steps:
     - uses: actions/checkout@main
 
-    - name: Run testProject Agent for Login Tests
+    - name: Failing job Tests
       env:
         TP_API_KEY: ${{ secrets.TP_API_KEY }}
         APPLICATION_URL: ${{ secrets.APPLICATION_URL }} 
-        JOB_ID: Q9WdIN3EEUyE437qx6fA9g
+        JOB_ID: 1vCI1WAo7U6X7Z0Oh4oMwQ
       run: |
         envsubst < .github/ci/docker-compose.yml > docker-compose.yml
         export TEST_RESULT=".github/testresults"
@@ -33,5 +34,6 @@ jobs:
         EXECUTION_ID=`echo ${EXECUTION_STRING##* }`
         curl -X GET "https://api.testproject.io/v2/projects/${{ secrets.TP_PROJECT_ID }}/jobs/${JOB_ID}/reports/${EXECUTION_ID}?details=true&format=TestProject" -H "accept: application/json" -H "Authorization: ${{ secrets.TP_API_KEY }}" | jq > ${TEST_RESULT}/login${EXECUTION_ID}.json
         RESULT=$(jq .resultType ${TEST_RESULT}/login${EXECUTION_ID}.json | sed 's/^.//;s/.$//')
-        if [$RESULT = 'Failed']; then echo "login test failed" && cat ${TEST_RESULT}/login${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
+        echo $RESULT
+        if [ $RESULT='Failed' ]; then echo "login test failed" && cat ${TEST_RESULT}/login${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
         rm ${TEST_RESULT}/login${EXECUTION_ID}.json
