workflow dispatch in login test moved up

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,7 +7,7 @@ name: Failing job Tests
 on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
-  
+
   # Triggers the workflow on push or pull request events but only for the master branch
   push:
     branches: [ master ]
@@ -32,8 +32,8 @@ jobs:
         export TEST_RESULT=".github/testresults"
         EXECUTION_STRING=$(docker-compose -f docker-compose.yml up --abort-on-container-exit | grep 'Downloaded execution package')
         EXECUTION_ID=`echo ${EXECUTION_STRING##* }`
-        curl -X GET "https://api.testproject.io/v2/projects/${{ secrets.TP_PROJECT_ID }}/jobs/${JOB_ID}/reports/${EXECUTION_ID}?details=true&format=TestProject" -H "accept: application/json" -H "Authorization: ${{ secrets.TP_API_KEY }}" | jq > ${TEST_RESULT}/login${EXECUTION_ID}.json
+        curl -X GET "https://api.testproject.io/v2/projects/${{ secrets.TP_PROJECT_ID }}/jobs/${JOB_ID}/reports/${EXECUTION_ID}?details=true&format=TestProject" -H "accept: application/json" -H "Authorization: ${{ secrets.TP_API_KEY }}" | jq > ${TEST_RESULT}/fail${EXECUTION_ID}.json
         RESULT=$(jq .resultType ${TEST_RESULT}/login${EXECUTION_ID}.json | sed 's/^.//;s/.$//')
         echo $RESULT
-        if [ $RESULT = 'Failed' ]; then echo "Always failing test failed" && cat ${TEST_RESULT}/login${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
-        rm ${TEST_RESULT}/login${EXECUTION_ID}.json
+        if [ $RESULT = 'Failed' ]; then echo "Always failing test failed" && cat ${TEST_RESULT}/fail${EXECUTION_ID}.json | jq && exit 1; else echo "Test passed"; fi
+        rm ${TEST_RESULT}/fail${EXECUTION_ID}.json
